quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.max-size=16
quarkus.webauthn.enable-login-endpoint=true
quarkus.webauthn.enable-registration-endpoint=true

quarkus.flyway.migrate-at-start=true
quarkus.flyway.connect-retries=3
quarkus.flyway.table=flyway_quarkus_history

quarkus.webauthn.user-verification=required
quarkus.webauthn.resident-key=required
quarkus.webauthn.authenticator-attachment=platform
quarkus.webauthn.attestation=none

quarkus.webauthn.session-timeout=30m
quarkus.webauthn.cookie-same-site=strict

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.swagger-ui.enabled=true

quarkus.smallrye-openapi.info-title=Quarkus Utils API
%test.quarkus.smallrye-openapi.info-title=Example API (test)
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=Quarkus Utils API for several Quarkus Featues including WebAuthn, OpenAPI, and more.
quarkus.smallrye-openapi.info-terms-of-service=Free to use for any purpose, but not liable for any issues that may arise from using this API.
quarkus.smallrye-openapi.info-contact-email=doogle-oss@outlook.com
quarkus.smallrye-openapi.info-contact-name=Quark Utils API Support
quarkus.smallrye-openapi.info-contact-url=https://github.com/doogle-oss
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html

quarkus.smallrye-graphql.ui.enabled=true